spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
# Enabling H2 Console
  h2:
    console:
       enabled: true
       path: /h2
server:
  port: 8083

logging:
  file: logs/application.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.cts.mc: INFO
  
swagger:
   api-info:
       title: Order Service Api Documentation
       description: Order Test API Details
       version: v1.0
       termsOfServiceUrl: order
       contact:
          name: Order
          email: Uttam.Ghorai@cognizant.com
       license: Apache 2.0
       licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
      
  